include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true # Avoid using print statements in production code
    avoid_unnecessary_containers: true # Prevent the use of unnecessary Container widgets
    avoid_web_libraries_in_flutter: true # Disallow using web-only libraries in Flutter
    no_logic_in_create_state: true # Encourage keeping logic outside createState
    prefer_const_constructors_in_immutables: true # Prefer const constructors for immutable classes
    sized_box_for_whitespace: true # Use SizedBox instead of Containers for spacing
    sort_child_properties_last: true # Place child properties last in widget constructors
    use_build_context_synchronously: true # Warn if BuildContext is used incorrectly in async code
    use_full_hex_values_for_flutter_colors: true # Require full hex values for Flutter colors
    use_key_in_widget_constructors: true # Enforce the use of keys in custom widgets4
    prefer_single_quotes: true # Enable code complexity limits
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_null_checks: true
    avoid_function_literals_in_foreach_calls: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_shadowing_type_parameters: true
formatter:
  page_width: 80