name: Sync my_structure from mason

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync_my_structure_mason:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: my_structure_mason
          token: ${{ secrets.ACTIONS_PUSH_TOKEN }}

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Sync core from lib/core
        run: |
          rm -rf bricks/core_brick/__brick__/core
          cp -r bricks/core_brick/__brick__/core ../lib/core
          cp -r ../lib/core bricks/core_brick/__brick__/core

      - name: Commit and push if changes exist
        env:
          TOKEN: ${{ secrets.ACTIONS_PUSH_TOKEN }}
        run: |
          git add bricks/core_brick/__brick__/core
          git diff-index --quiet HEAD || git commit -m "🔄 Sync core from lib/core (auto update from master)"
          git push https://x-access-token:${TOKEN}@github.com/OmarAly92/my_structure.git HEAD:my_structure_mason